{
 "title": "horcrux from Cumulo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "options": {
    "content": "\n<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/cumulocolor.jpg\" alt=\"Logo\" style=\"height: 100px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>horcrux metrics</h2>\n    <h5>from <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n</div>"
   }
  },
  {
   "title": "Total Times Combined Signature is Invalid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_error_total_invalid_signatures",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Times Cosigners doesn't reach threshold",
   "type": "stat",
   "description": "This metric counts the total number of times the number of co-signatories does not reach the threshold necessary to validate an operation or transaction. In other words, this metric increases each time an action that requires the signature of multiple parties cannot be completed because there are not enough signatures from the required parties.",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_error_total_insufficient_cosigners",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics that don't always correspond to block time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Seconds Since Last Local Start Sign (May increase beyond block time, Rarely important) ",
   "type": "stat",
   "description": "signer_seconds_since_last_local_sign_start_time: Measures the time in seconds since the last local signing process started. This metric is useful to observe when a cosigner starts the signing process of a block.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_seconds_since_last_local_sign_start_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last block height signed",
   "type": "stat",
   "description": "Indicates the last block height for which a precommit was signed. A precommit is a signal that a validator agrees with the state of the blockchain at that specific height and is ready to move forward.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "signer_last_precommit_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Seconds Since Last Local Finish Sign (Should stay below 2 * Block Time)",
   "type": "stat",
   "description": "Seconds Since Last Local Finish Sign (Should stay below 2 * Block Time)",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_seconds_since_last_local_sign_finish_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Seconds Since Last Local Ephemeral Share Sign (Should not increase beyond block time) ",
   "type": "timeseries",
   "description": "Each block, Nonce Secrets are shared between Cosigners. Monitoring 'signer_seconds_since_last_local_ephemeral_share_time' and ensuring it does not exceed the block time will allow you to know when a Cosigner was not contacted for a block.\nIf high, may indicate raft joining issue for CoSigner",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "signer_seconds_since_last_local_ephemeral_share_time",
     "legendFormat": "s{{share}}/{{instance}}"
    }
   ]
  },
  { "title": "Watching For Cosigner Trouble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Last precommit round to be signed",
   "type": "timeseries",
   "description": "Represents the last precommit round that was signed. Rounds are iterations within the same block height to reach consensus.\n0 Indicates that the last precommit round that was signed was round 0, which may imply that consensus was reached in the first round for that specific block height.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "signer_last_precommit_round", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consecutive Threshold Signature Parts Missed",
   "type": "timeseries",
   "description": "will note when the leader is not able to get a signature from the peer. If 'signer_total_missed_ephemeral_shares' increases to a high number, this may indicate a larger issue.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "signer_missed_ephemeral_shares", "legendFormat": "{{peerid}}" }
   ]
  },
  { "title": "Checking Signing Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Seconds taken to get threshold of cosigners available",
   "type": "timeseries",
   "description": "This metric measures the time it takes for the system to reach the threshold necessary for a block to be considered valid. The lower these values, the faster the availability threshold is reached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "signer_sign_block_threshold_lag_seconds{quantile=\"0.9\"}",
     "legendFormat": "s{{share}}/{{instance}} -> {{peerid}}"
    }
   ]
  },
  {
   "title": "Seconds taken to get all cosigner signatures",
   "type": "timeseries",
   "description": "After reaching the threshold, all cosigners should sign quickly",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "signer_sign_block_cosigner_lag_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time taken to get cosigner signature",
   "type": "timeseries",
   "description": "If 'signer_sign_block_cosigner_lag_seconds' takes a significant amount of time, you can check the performance of each cosigner as it is seen by the raft leader. High numbers may indicate a high latency link or a resource. This metric is only available on the Leader and will report 'NaN' on followers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "signer_cosigner_sign_lag_seconds{quantile=\"0.9\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Raft data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total Times Signer is Raft Leader",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "signer_total_raft_leader", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Raft Leader Election Timeout",
   "type": "timeseries",
   "description": "Counts the total number of times the Raft leader has failed to be elected due to lack of peers or failure to reach consensus in the expected time.\n0 This indicates that there have been no failures to elect the leader due to lack of peers, which is a sign of stability in the Raft cluster.\n",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "signer_total_raft_leader_election_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Signer Raft Not Leader",
   "type": "timeseries",
   "description": "Shows the total number of times the signatory has not been the leader and therefore acted as a proxy sending signatures to the Raft leader.",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 53 },
   "targets": [
    { "expr": "signer_total_raft_not_leader", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Sentry connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  },
  {
   "title": "TCP connection attempts to sentinel nodes",
   "type": "timeseries",
   "description": "Counts the total number of TCP connection attempts to sentinel nodes. Sentinels are nodes used to protect validators from direct attacks, acting as a proxy between the validator and the rest of the network.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "signer_total_sentry_connect_tries",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "TCP connection attempts to sentinel nodes",
   "type": "timeseries",
   "description": "Counts the total number of TCP connection attempts to sentinel nodes. Sentinels are nodes used to protect validators from direct attacks, acting as a proxy between the validator and the rest of the network.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    { "expr": "signer_sentry_connect_tries", "legendFormat": "{{instance}}->>{{node}}" }
   ]
  }
 ]
}